#! /bin/bash
#Switch odoo version
cd ../design-themes && git checkout $1 && git pull && git clean -dfx
cd ../enterprise && git checkout $1 && git pull && git clean -dfx
cd ../odoo && git checkout $1 && git pull && git clean -dfx
